### ISSUE TITLE
Performance Test Pie chart not working

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#21]
I tested on the installation at https://sgmstest-subdomain.com/notmu and the pie chart in the Performance Test section is not working properly. On my end it is always showing 100% Other, which is not normal:

https://screenshots.firefox.com/pigaHNHO1ikuPvRG/sgmstest-subdomain.com

I tested by selecting the option "Advanced Scan" and then "Test as a logged user".

**Comment by kojuharov** [comment]
Just to add - I tested with both Dynamic Cache on and off, and with all PHP versions above 5.5 - 5.5., 5.6, 7.0, 7.1 and 7.2.
The result is the same

**Comment by Rarst** [comment]
I see the issue on live site, for some reason JS object with data isn't getting loaded. Not sure what is causing it yet.

Could you please update plugin source on site to the latest? `develop-features` branch.

**Comment by kojuharov** [comment]
Done, plugin updated from the develop-features branch to the latest version. Tested and the problem still persists as well as the whole layout of the page is a little messed up, which I assume is related to the JS objects, so I will not post any new bugs about this until you check it.

**Comment by Rarst** [comment]
Ok, wasn't entirely right, JS object _does_ get loaded but data is blank because pages under test don't properly collect and output timing data.

I seem to have narrowed it down to following conditional which I use to read cookie value: `filter_input( INPUT_SERVER, 'HTTP_X_SG_OPTIMIZER_TEST', FILTER_VALIDATE_INT )`

Any insight why this might be failing in your server environment?

**Comment by Rarst** [comment]
Fixed in https://github.com/Rarst/sg-cachepress/commit/e0aba1b20f12051f3035b955c50625e07fe94cfc
