### ISSUE TITLE
UX Changes / Issues

### ISSUE THREAD

**Issue by pandjarov** [Rarst/sg-cachepress#30]
I will summarize the issues and changes for the UX in this ticket:

- Generally, the results are a bit strange, is that only the dom? I would like to get full load results, at this current state numbers aren't really useful for the customer.
Fastest Page: https://queenswinehouse.com/love/ 0.01s

- The Pie Chart in the test does not provide useful information.  The entire table with plugins and themes information is missing. I would like to have a expand/collapse groups: Core, Plugins, Themes. Right now they're very strangely grouped, Core and Plugins for example.

- On Scan results, please add environment info from the time test was done so you can easily see changes. For example:
Dynamic Cache: ON, PHP 7.1, gZIP: ON, Browser Cache: ON

- On MS environment, that can be seen in the Edit -> Settings screen of the page:
Sg Wpephpcompat.current Php Version	7.0
Sg Wpephpcompat.prev Php Version	5.6
Sg Wpephpcompat.test Version	7.0
Sg Wpephpcompat.only Active	yes

Is there any way we can delete those from there?

- On MS environment, that can be seen in the Edit -> Settings screen of the page:

Can we move all our settings under the Quota field? And can we put a title above our group of settings, like <h3>SG Optimizer Settings</h3>

- On MS environment, please return the SG Optimizer main page - and make a view for it or use the existing one with conditional. 

- ON MS environment, please add the SuperCacher page - we need it to be able to set defaults for new sites - caching and autoflush

- Please, split Logs on a different page with it's own view that can be styled. 

- On Logs page, improve this type of logging: 2017-10-02T09:30:19+00:00 admin updated settings on http://sgmstest-subfolder.com/kojuharov3

Need to know which settings were updated.

- On MS environment,

**Comment by Rarst** [comment]
This seems like it lost some bits in copy paste?.. :) Like a picture expected for settings and just stops at the end?

> Generally, the results are a bit strange, is that only the dom? I would like to get full load results, at this current state numbers aren't really useful for the customer.

As previously discussed it is effectively page generation/serving time plus network overhead (which is minimal since we are doing request locally from servers point of view).

> The Pie Chart in the test does not provide useful information. The entire table with plugins and themes information is missing. I would like to have a expand/collapse groups: Core, Plugins, Themes. Right now they're very strangely grouped, Core and Plugins for example.

Define useful information?

We've been over the original mockup. As of right now core simply doesn't _have_ a way to precisely measure individual plugin load, only the plugin load stage in total. I am happy to add any events you would like, as long as _core has hooks_ for them.

The order in pie chart is that of how it happens during core load. Naturally that and colors/whatever can be tweaked, I just went off original mockup.

On it as for the rest. :)

**Comment by pandjarov** [comment]
> As previously discussed it is effectively page generation/serving time plus network overhead (which is minimal since we are doing request locally from servers point of view).

Can we add resource loading in that time? LIke complete page load?

> Define useful information?

Have the actual plugins and how much time they take to load is probably the most important one.

**Comment by Rarst** [comment]
Sorry, dental stuff knocked my head out for couple of days, catching up. 🤐

> Can we add resource loading in that time? LIke complete page load?

I gave this some thought and my impression is that you keep circling to "browser-centric" take on performance, that is what happens when _browser_ downloads and processes a web page.

Problem is WP plugin isn't a browser. It is just impractically complicated to make something that _acts_ like a browser, due to enormous complexity of everything that modern browser does. Any performance tool that does browser-level performance just does it _with_ a (headless) browser on server.

I think page generation time is reasonable focus for our scope here because it is:

 - good fit for what plugin _can_ measure
 - performance priority anyway, in my opinion (if your page source takes seconds to what's _in it_ isn't even coming into play)
 - most impacted by tools you as a hosting offer (PHP version, object cache, reverse proxy)

> Have the actual plugins and how much time they take to load is probably the most important one.

This is something I **very** much would like to see myself, but as I mentioned to you before it's unfortunately cannot be measured due to a way WP core performs plugin load.

It would be a minor change to core to enable it, but before (if ever) that change happens, this isn't a possibility in user land PHP code.

Trac ticket for it that I mentioned before: https://core.trac.wordpress.org/ticket/41346

**Comment by pandjarov** [comment]
Could you check the P3 profiler plugin? It actually shows how much time it takes for every plugin to load. That's a must-have information here.

As to the first part, the generation time is completely useless. Maybe try to do it with curl, or something else but it doesn't make sense to show that information to the customer. Furthermore, they won't be able to see any difference from enabling gZIp for example, or the browser caching and so on...

**Comment by Rarst** [comment]
> Could you check the P3 profiler plugin? It actually shows how much time it takes for every plugin to load. That's a must-have information here.

I am well familiar with it. The mechanism it uses is PHP ticks, which produces results that are best described as completely bogus (which even its developer eventually agreed with). What that plugin mostly accomplished is a lot of pissed of developers of popular plugins who got a support spike of "performance" issues that just weren't real.

> As to the first part, the generation time is completely useless.

I disagree. Unreasonable page generation time is both highly typical problem with WP sites and _precedes all other_ performance problems. It doesn't matter in the least how assets load if it takes multiple seconds to just get a page source.

> Furthermore, they won't be able to see any difference from enabling gZIp for example, or the browser caching and so on...

These are again browser-centric and won't even be consistent between _different_ browsers. These are the feature that make improvement on statistical level, but aren't too practical to measure individually.

**Comment by Rarst** [comment]
> On Scan results, please add environment info

Done.

> On MS environment, that can be seen

Removed. Hardcoded in source unfortunately to took a bit of jQuery to get rid of.

> Can we move all our settings under the Quota field? And can we put a title above

Done.

> Please, split Logs on a different page with it's own view that can be styled.

Done.

> On Logs page, improve this type of logging

Done.

> On MS environment, please return the SG Optimizer main page - and make a view for it or use the existing one with conditional.
> ON MS environment, please add the SuperCacher page - we need it to be able to set defaults for new sites - caching and autoflush

Could you please clarify behavior on these two? I thought I follow but now not so sure. Are we atlking network admin? Individual admin when on multisite? Which pages precisely?

**Comment by pandjarov** [comment]
> I am well familiar with it. The mechanism it uses is PHP ticks, which produces results that are best described as completely bogus (which even its developer eventually agreed with). What that plugin mostly accomplished is a lot of pissed of developers of popular plugins who got a support spike of "performance" issues that just weren't real.


I am aware of that. Just can't show the customer any difference from the changes they make - gzip, browser caching with the test which mitigates its purpose. Can you give it one more try please? Maybe two curl requests? Just shooting in the dark here.

**Comment by Rarst** [comment]
> Just can't show the customer any difference from the changes they make - gzip, browser caching with the test which mitigates its purpose.

The benefit of these features is highly inconsistent between users. As results it is not productive to express them as specific _time_ value/difference (outside of measuring complete in-browser load/render and even then it's narrowly applicable to connection/location).

This is why popular tools (Google PageSpeed, etc) express such features as a _score_, not time. Their scores are _explicitly independent_ from time performance, because these improvements are only meaningfully applicable in aggregate, on statistical scale between many users, repeat visits to the site, and so on.

I think the current iteration already provides meaningful feedback on such features (_X is disabled, you should enable X because for reasons Y_).

If you want _quantifiable_ numeric feedback on them then you probably want a score model, _separate_ from time benchmarks. For which integration with PageSpeed Insights API or something would make more sense than building this within a WP plugin.

Overall my take at this point would be just to ship combination of time benchmark and recommendations on remainder of features. The idea of expressing _everything_ in some kind of single number that would be any helpful to a user just well exceeds initial spec for this feature.

**Comment by pandjarov** [comment]
OK leave this as it is.

**Comment by Rarst** [comment]
Added default caching settings for a new site to network admin in https://github.com/Rarst/sg-cachepress/commit/789bd0409a61270ab6ef1ae620aec5043927498a
