### ISSUE TITLE
Force HTTPS not working on main site

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#38]
Hello,

We discovered a bug with the Force HTTPS functionality of the SG Optimizer plugin.

Whatever you set the Force HTTPS option to - it has no effect for any of the subsites or the main one.

You can easily recreate at https://sgmstest-subdomain.com/wp-admin/network/site-settings.php?id=1. Simply scroll down to the bottom of the page and disable the Force HTTPS option and you will see that nothing will happen.

You can also pick any of the subsites in that installation and test with them, for example - https://sgmstest-subdomain.com/wp-admin/network/site-settings.php?id=4. The problem is present there as well.

**Comment by Rarst** [comment]
Unfortunately I am not available this week due to travel. Discussed it with @pandjarov , will see how it works out.

**Comment by kojuharov** [comment]
The issue is not that urgent, so we will wait for you to review it next week.

**Comment by Rarst** [comment]
Hey, sorry for delay. I went over issue and here is current state of it:

1. Force HTTPS made use of .htaccess modification for the redirects of visited link
2. We disabled that for multisite specifically, due to impracticality of generating redirect rules for essentially arbitrary amount of sites, possibly with arbitrary domains assigned, see https://github.com/Rarst/sg-cachepress/commit/adf9a5c408fb361f3781743fddfc393bfab29a46
3. As far as I see from going over discussion that was done in favor of core redirecting to correct protocol
4. Reviewing the core code the scheme changes seems to have been dropped from redirects, see https://core.trac.wordpress.org/changeset/30090
5. However that change seems to significantly predate our development, at which point I am confused how this seems to have worked and passed testing

Overall I feel this might be pushing limits of reasonable automation in multisite context.

The possible solution would be to add our own PHP-level redirect, analogous to previously available core functionality. It was dropped from core due to possible issues with reverse proxies (see linked issue) but since SG is in control of their server configuration that isn't something to worry about?

**Comment by kojuharov** [comment]
Hello,

It is very important to be able to force HTTPS and this is one of the main requirements for the plugin. We need this functionality to work.

If you believe there is a reliable way of achieving this by using .htaccess rules - perfect, implement that. If not - then it should be done via a PHP-level redirect like you explained above.

**Comment by Rarst** [comment]
I don't think .htaccess can reasonably do this (that's why we dropped it in first place), will work on PHP redirect.

**Comment by Rarst** [comment]
Found related bug with Force HTTPs setting running out of sync due to .htaccess skip. Old code apparently doesn't like it and also inconsistently treats the state as either explicit `sg_cachepress_ssl_enabled` option or implicit state of WP URL options via respective check. Will get that fixed.

Implementing redirect itself is not complicated, however determining the _right_ context for it to execute is. Working through things I can think of (such as being on correct multisite, REST API, POST requests, etc) so it does what it needs to without messing anything up.

PS travelling to a WordCamp tomorrow, but will have computer with me this trip so will be reachable / chipping on this.
