### ISSUE TITLE
Dynamic Caching not working on mapped domains

### ISSUE THREAD

**Issue by pandjarov** [Rarst/sg-cachepress#7]
In the domain mapping installation the dynamic caching doesn't work at all.

it works on the main domain: https://sgmstest-mapdomain.com

but not on the mapped one: https://sgmstest-mapped.com

**Comment by Rarst** [comment]
Could you please clarify is this on _WordPress_ side or on _caching layer_ side?

What plugin currently doesn't do or does in an invalid way in current implementation?

Though intuitively I get that mapped domain looks sufficiently different to throw something off, I am not sure what is _exact_ underlying problem here from technical point of view.

**Comment by pandjarov** [comment]
On the WP side, that will be fixed by the other ticket we just discussed.

**Comment by pandjarov** [comment]
Tested, fixed.
